#!/usr/bin/env python
# coding: utf-8

# In[4]:


#helpful packages
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


# In[5]:


df=pd.read_csv('Iris.csv')


# In[8]:


df.head()


# In[9]:


#dropping not imp columns
df=df.drop(columns=['Id'])


# In[10]:


df.head()


# In[11]:


df.shape


# In[12]:


df.isnull().sum()


# In[14]:


#Exploratory data analysis
df['Species'].value_counts()


# In[16]:


df['Species'].value_counts().plot.bar()


# In[18]:


x=df.iloc[:,0:4]
y=df.iloc[:,-1]


# In[19]:


#Train and test split
from sklearn.model_selection import train_test_split


# In[20]:


x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)


# In[21]:


x_train


# In[22]:


y_train


# In[23]:


#Logistic Regression on data
from sklearn.linear_model import LogisticRegression


# In[24]:


lr=LogisticRegression()
lr.fit(x_train,y_train)


# In[25]:


y_pred=lr.predict(x_test)


# In[26]:


from sklearn.metrics import accuracy_score


# In[27]:


accuracy_score(y_test, y_pred)*100


# In[28]:


#graph comparing old and new data(after training)
sns.histplot(y_test,color='y')
sns.histplot(y_pred,color='g')


# In[ ]:
